steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/uplifted-backend', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/uplifted-backend']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'uplifted-backend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/uplifted-backend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - '_FIREBASE_TYPE=$_FIREBASE_TYPE,_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID,_FIREBASE_PRIVATE_KEY_ID=$_FIREBASE_PRIVATE_KEY_ID,_FIREBASE_PRIVATE_KEY=$_FIREBASE_PRIVATE_KEY,_FIREBASE_CLIENT_EMAIL=$_FIREBASE_CLIENT_EMAIL,_FIREBASE_CLIENT_ID=$_FIREBASE_CLIENT_ID,_FIREBASE_AUTH_URI=$_FIREBASE_AUTH_URI,_FIREBASE_TOKEN_URI=$_FIREBASE_TOKEN_URI,_FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$_FIREBASE_AUTH_PROVIDER_X509_CERT_URL,_FIREBASE_CLIENT_X509_CERT_URL=$_FIREBASE_CLIENT_X509_CERT_URL,_FIREBASE_UNIVERSE_DOMAIN=$_FIREBASE_UNIVERSE_DOMAIN'

# Specify the logs bucket
# logsBucket: NONE

# Specify logging options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout for the build process
timeout: '1200s'
