steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/uplifted-backend', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/uplifted-backend']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'uplifted-backend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/uplifted-backend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# Substitutions (optional, can be overridden during build trigger setup)
substitutions:
  _SERVICE_NAME: 'uplifted-backend-service'
  _REGION: 'us-central1'

# Timeout for the build process.
# not sure what else to do
timeout: '1200s'
